version: '3'

services:
  db:
    image: postgres:12
    environment:
      POSTGRES_DB: northwind
      POSTGRES_USER: northwind_user
      POSTGRES_PASSWORD: thewindisblowing
    volumes:
      - ./dbdata:/var/lib/postgresql/data
      - ./data/northwind.sql:/docker-entrypoint-initdb.d/northwind.sql
    ports:
      - 5432:5432


  db-container:
    image: postgres:12
    environment:
      POSTGRES_DB: indicium
      POSTGRES_USER: id_indicium
      POSTGRES_PASSWORD: password
    volumes:
      - ./dbdata:/var/lib/postgresql/data
    ports:
      - 5440:5432
  

  airflow:
      image: puckel/docker-airflow:1.10.9
      container_name: airflow-container
      restart: always
      depends_on:
        - db
        - db-container
      environment:
        - AIRFLOW_CORE_EXECUTOR=LocalExecutor
      volumes:
        - ./data:/data
        - ./airflow:/usr/local/airflow/dags
      ports:
        - "8080:8080"